In [3]:
import pandas as pd
import numpy as np
import os
import gensim
import nltk

In [4]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\abc.zip.
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers\averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers\averaged_per

True

In [6]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [7]:
for file in os.listdir('./data/'):
    print(file)

story1.txt
story2.txt


In [9]:
f = open(r"data/story1.txt",encoding='unicode_escape')

In [10]:
f

<_io.TextIOWrapper name='data/story1.txt' mode='r' encoding='unicode_escape'>

In [11]:
corpus =f.read()

In [12]:
corpus

'Once upon a time, there was a young boy named Arjun who lived in a small town surrounded by hills and rivers. He was very curious about how things worked and always asked questions. His parents often smiled at his curiosity and encouraged him to learn more.\n\nEvery day after school, Arjun would sit with his books and explore different topics. He was especially fascinated by science and technology. He wanted to understand how machines think and whether they could become as intelligent as humans.\n\nOne day, while browsing through an old computer at school, Arjun discovered the concept of artificial intelligence. He read about how machines can learn from data, recognize patterns, and even make decisions. This idea completely amazed him.\n\nHe started imagining a future where machines could help humans solve complex problems. That day, he made a decision that he wanted to become an AI engineer.\n\nArjun began learning programming using free resources. At first, everything seemed difficu

In [13]:
sent_tokenize(corpus)

['Once upon a time, there was a young boy named Arjun who lived in a small town surrounded by hills and rivers.',
 'He was very curious about how things worked and always asked questions.',
 'His parents often smiled at his curiosity and encouraged him to learn more.',
 'Every day after school, Arjun would sit with his books and explore different topics.',
 'He was especially fascinated by science and technology.',
 'He wanted to understand how machines think and whether they could become as intelligent as humans.',
 'One day, while browsing through an old computer at school, Arjun discovered the concept of artificial intelligence.',
 'He read about how machines can learn from data, recognize patterns, and even make decisions.',
 'This idea completely amazed him.',
 'He started imagining a future where machines could help humans solve complex problems.',
 'That day, he made a decision that he wanted to become an AI engineer.',
 'Arjun began learning programming using free resources.',


In [14]:
raw_sent = sent_tokenize(corpus)

In [15]:
for i in raw_sent:
  print(simple_preprocess(i))

['once', 'upon', 'time', 'there', 'was', 'young', 'boy', 'named', 'arjun', 'who', 'lived', 'in', 'small', 'town', 'surrounded', 'by', 'hills', 'and', 'rivers']
['he', 'was', 'very', 'curious', 'about', 'how', 'things', 'worked', 'and', 'always', 'asked', 'questions']
['his', 'parents', 'often', 'smiled', 'at', 'his', 'curiosity', 'and', 'encouraged', 'him', 'to', 'learn', 'more']
['every', 'day', 'after', 'school', 'arjun', 'would', 'sit', 'with', 'his', 'books', 'and', 'explore', 'different', 'topics']
['he', 'was', 'especially', 'fascinated', 'by', 'science', 'and', 'technology']
['he', 'wanted', 'to', 'understand', 'how', 'machines', 'think', 'and', 'whether', 'they', 'could', 'become', 'as', 'intelligent', 'as', 'humans']
['one', 'day', 'while', 'browsing', 'through', 'an', 'old', 'computer', 'at', 'school', 'arjun', 'discovered', 'the', 'concept', 'of', 'artificial', 'intelligence']
['he', 'read', 'about', 'how', 'machines', 'can', 'learn', 'from', 'data', 'recognize', 'patterns',

In [47]:
folder_path = r"data"
story = []
for filename in os.listdir(folder_path):
  file_path=os.path.join(folder_path,filename)
  with open(file_path,encoding='unicode_escape') as f:
    corpus=f.read()
  raw_sent=sent_tokenize(corpus)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [18]:
story

[['once',
  'upon',
  'time',
  'there',
  'was',
  'young',
  'boy',
  'named',
  'arjun',
  'who',
  'lived',
  'in',
  'small',
  'town',
  'surrounded',
  'by',
  'hills',
  'and',
  'rivers'],
 ['he',
  'was',
  'very',
  'curious',
  'about',
  'how',
  'things',
  'worked',
  'and',
  'always',
  'asked',
  'questions'],
 ['his',
  'parents',
  'often',
  'smiled',
  'at',
  'his',
  'curiosity',
  'and',
  'encouraged',
  'him',
  'to',
  'learn',
  'more'],
 ['every',
  'day',
  'after',
  'school',
  'arjun',
  'would',
  'sit',
  'with',
  'his',
  'books',
  'and',
  'explore',
  'different',
  'topics'],
 ['he',
  'was',
  'especially',
  'fascinated',
  'by',
  'science',
  'and',
  'technology'],
 ['he',
  'wanted',
  'to',
  'understand',
  'how',
  'machines',
  'think',
  'and',
  'whether',
  'they',
  'could',
  'become',
  'as',
  'intelligent',
  'as',
  'humans'],
 ['one',
  'day',
  'while',
  'browsing',
  'through',
  'an',
  'old',
  'computer',
  'at',
  'sc

In [48]:
len(story)

60

In [20]:
story[0]

['once',
 'upon',
 'time',
 'there',
 'was',
 'young',
 'boy',
 'named',
 'arjun',
 'who',
 'lived',
 'in',
 'small',
 'town',
 'surrounded',
 'by',
 'hills',
 'and',
 'rivers']

In [21]:
story[1]

['he',
 'was',
 'very',
 'curious',
 'about',
 'how',
 'things',
 'worked',
 'and',
 'always',
 'asked',
 'questions']

In [23]:
# sunny->100
# Divyansh->6
# Rahul->3

In [24]:
# Word2Vec(..., sg=0)  # CBOW #by default
# Word2Vec(..., sg=1)  # Skip-gram

In [25]:
# custom_model =gensim.models.Word2Vec(
#     window=10,
#     min_count=5,
#     vector_size=150
    
# )

## these all the value are the hyperparameter

In [49]:
custom_model =gensim.models.Word2Vec(
    window=10,
    min_count=1,
    vector_size=150
    
)

In [50]:
custom_model.build_vocab(story)

In [28]:
custom_model.corpus_count

44

In [55]:
custom_model.train(story, total_examples=custom_model.corpus_count, epochs=100)

(49078, 70400)

(119, 2610)
Part	Meaning
119	number of documents
2610	number of unique words

In [30]:
custom_model.wv["arjun"]

array([ 2.6652003e-03,  2.8245403e-03,  6.5046512e-03, -2.9594905e-03,
       -9.7900024e-04, -4.8407973e-03, -6.5083457e-03, -5.5592735e-03,
       -8.9224969e-04, -4.1782702e-03,  3.3547548e-03, -4.0903729e-03,
        1.4304204e-03,  4.5200656e-04, -2.5152317e-03, -9.2202768e-04,
        6.7886058e-03,  6.0640317e-03, -3.1183886e-03,  6.2328507e-03,
       -3.8982404e-03,  3.8104909e-03, -1.7123157e-03,  2.6284952e-03,
        1.9528873e-03,  4.4414029e-03, -1.9265332e-03,  5.5350247e-03,
        4.9215574e-03, -6.6542877e-03, -5.1630284e-03, -5.1484681e-03,
        1.7946371e-03, -2.1244455e-03, -4.9253558e-03, -5.3152777e-03,
        5.9422376e-03,  1.4605242e-03, -6.2021515e-03, -3.4563520e-03,
        2.0429585e-03, -3.1655910e-03,  3.1986262e-03, -2.9756571e-03,
        1.8925727e-03, -5.4666759e-03,  4.1482230e-03,  3.1765231e-03,
        5.7671935e-04,  2.1005478e-03, -5.7784277e-03,  1.4107935e-03,
       -6.5248570e-04, -6.0869828e-03, -6.3044881e-03, -8.4901601e-04,
      

In [31]:
len(custom_model.wv["arjun"])

150

In [32]:
custom_model.wv["farmers"]

array([ 5.3552012e-03,  5.1741251e-03, -3.7444988e-03, -5.3383922e-03,
        5.3446591e-03, -2.4728815e-03, -2.7462593e-03,  5.1985038e-03,
        3.4517427e-03,  2.6663404e-03, -7.2656100e-04,  5.7831742e-03,
        5.4437052e-03,  4.5913379e-03,  5.8574476e-03, -4.0924489e-03,
        7.6572871e-04, -1.1296838e-03,  4.1231043e-03,  6.7220512e-03,
        3.2720149e-03,  2.5860902e-03,  4.6602734e-03,  4.2115678e-03,
       -2.6615884e-05, -5.6931456e-03, -1.7418164e-03,  5.7782629e-03,
       -3.4753229e-03,  4.4435813e-04,  3.3774804e-03, -4.6840506e-03,
        5.3546894e-03,  7.1781990e-04,  1.3665642e-03,  5.5706510e-03,
        1.2574379e-03,  6.7592302e-04, -6.3033001e-03,  6.3908747e-03,
       -6.5778191e-03,  5.6763496e-03,  3.1340546e-03, -1.8878994e-04,
       -5.1870192e-03,  6.1012367e-03, -9.1861980e-04,  3.5516135e-03,
       -2.0211558e-03, -3.2087907e-03,  1.2794635e-04, -5.4150079e-03,
       -4.4867937e-03, -6.1870348e-03,  3.5145783e-03,  3.9377486e-04,
      

In [33]:
custom_model.wv["ai"]

array([ 6.4694928e-03,  4.2867009e-03, -6.2649641e-03, -4.7400910e-03,
       -5.6433072e-03,  2.8647000e-03,  6.0026781e-03, -3.1115666e-03,
       -6.1352323e-03, -7.8951259e-04, -1.7660653e-03,  8.7803073e-04,
        3.3544078e-03,  3.6037175e-04,  2.9718128e-03,  5.9011797e-03,
       -5.0911475e-03,  3.8697177e-03,  2.9713544e-04, -5.2706725e-03,
       -3.7234880e-03,  2.6527690e-03,  5.5481796e-03, -3.9958726e-03,
       -2.9267920e-03, -1.9155407e-03, -2.5687320e-03, -6.6827429e-03,
        9.4977091e-04, -5.2455161e-03, -3.9587040e-03,  2.9066112e-03,
       -3.8739103e-03, -2.2661083e-03,  1.6287505e-04,  6.2918616e-03,
       -3.3590635e-03,  6.7418907e-04, -4.6910672e-03,  4.1232849e-03,
        6.5253787e-03,  6.5594106e-03, -3.0211024e-03,  6.2871967e-03,
        4.8400024e-03, -2.2111238e-04, -2.4065801e-03,  1.0149500e-03,
        2.5681295e-03, -4.8076762e-03,  2.3136477e-03,  2.0338637e-03,
        4.6098503e-04, -1.7656884e-03,  1.6379752e-03,  3.8171078e-03,
      

In [34]:
custom_model.wv.most_similar("arjun")

[('curious', 0.2585282027721405),
 ('healthcare', 0.23024840652942657),
 ('that', 0.2119806557893753),
 ('their', 0.19668042659759521),
 ('predictions', 0.1965198814868927),
 ('how', 0.1962643712759018),
 ('passed', 0.18270263075828552),
 ('improvements', 0.162565216422081),
 ('decided', 0.16041719913482666),
 ('games', 0.15869300067424774)]

In [35]:
custom_model.wv.most_similar("ai")

[('using', 0.19991154968738556),
 ('complex', 0.19577597081661224),
 ('many', 0.19469530880451202),
 ('inspired', 0.18787147104740143),
 ('better', 0.17880965769290924),
 ('saw', 0.17642568051815033),
 ('happy', 0.1754019409418106),
 ('this', 0.1667207032442093),
 ('worked', 0.16653934121131897),
 ('knowledge', 0.1663874387741089)]

In [36]:
custom_model.wv.most_similar("engineer")

[('solve', 0.21200162172317505),
 ('decided', 0.2004907876253128),
 ('boy', 0.19899894297122955),
 ('were', 0.19713957607746124),
 ('build', 0.19529303908348083),
 ('learned', 0.1832837462425232),
 ('refining', 0.1758306920528412),
 ('shared', 0.1707114428281784),
 ('simple', 0.1691044420003891),
 ('named', 0.16117146611213684)]

In [37]:
custom_model.wv.most_similar("data")

[('stuck', 0.22219140827655792),
 ('world', 0.20422351360321045),
 ('became', 0.17875529825687408),
 ('idea', 0.1699761003255844),
 ('better', 0.1647794544696808),
 ('amazed', 0.1571594625711441),
 ('struggled', 0.15702030062675476),
 ('in', 0.15538378059864044),
 ('things', 0.15387021005153656),
 ('villages', 0.15295836329460144)]

In [38]:
custom_model.wv.doesnt_match(["arjun", "engineer", "programming", "farmers"])

'arjun'

In [39]:
custom_model.wv.doesnt_match(["data", "model", "system", "river"])

'system'

In [40]:
custom_model.wv.doesnt_match(["weather", "crops", "farmers", "technology"])

'crops'

In [42]:
# google-news-million of Artical
# neural and llm -> data hungry

In [52]:
custom_model.wv.similarity("ai", "technology")

np.float32(0.9982088)

In [53]:
custom_model.wv.similarity("arjun", "engineer")

np.float32(0.99834365)

In [57]:
custom_model.wv.similarity("maya", "invention")

np.float32(0.99305344)

## Assignment for this week

## add more data
## train for more epoch
## and check the accuracy of model
## check the embedding dimesion also

## inshort play with all the parameter

In [ ]:
# Check embedding dimension
print("Embedding dimension:", custom_model.wv['arjun'].shape)
print("Vector size parameter:", custom_model.vector_size)

# Additional accuracy checks
print("\n--- Model Accuracy Evaluation ---")

# 1. Similarity checks for related words
print("1. Similarity between 'ai' and 'technology':", custom_model.wv.similarity("ai", "technology"))
print("2. Similarity between 'arjun' and 'engineer':", custom_model.wv.similarity("arjun", "engineer"))
print("3. Similarity between 'engineer' and 'robot':", custom_model.wv.similarity("engineer", "robot"))
print("4. Similarity between 'maya' and 'invention':", custom_model.wv.similarity("maya", "invention"))

# 2. Most similar words
print("\n4. Words most similar to 'ai':", custom_model.wv.most_similar("ai", topn=5))
print("5. Words most similar to 'engineer':", custom_model.wv.most_similar("engineer", topn=5))

# 3. Word analogy (if possible)
try:
    result = custom_model.wv.most_similar(positive=['ai', 'robot'], negative=['human'], topn=1)
    print("\n6. Analogy: ai + robot - human =", result[0][0], f"(confidence: {result[0][1]:.3f})")
except KeyError as e:
    print(f"\n6. Analogy test failed: Missing word '{e}' in vocabulary")

print("\n--- Assignment Complete ---")
print("✅ Added more data (story3.txt)")
print("✅ Trained for more epochs (100)")
print("✅ Checked accuracy (similarities and evaluations above)")
print("✅ Checked embedding dimension (150)")

Embedding dimension: (150,)
Vector size parameter: 150

--- Model Accuracy Evaluation ---
1. Similarity between 'ai' and 'technology': 0.98310983
2. Similarity between 'arjun' and 'engineer': 0.99417895
3. Similarity between 'engineer' and 'robot': 0.9884598

4. Words most similar to 'ai': [('engineer', 0.9965968728065491), ('dreaming', 0.996273398399353), ('innovate', 0.9962103366851807), ('together', 0.9961941242218018), ('greater', 0.9958119988441467)]
5. Words most similar to 'engineer': [('ai', 0.9965968132019043), ('of', 0.9961541295051575), ('successful', 0.9945670962333679), ('techville', 0.9944010376930237), ('arjun', 0.9941790699958801)]

6. Analogy: ai + robot - human = dedication (confidence: 0.988)

--- Assignment Complete ---
✅ Added more data (story3.txt)
✅ Trained for more epochs (50)
✅ Checked accuracy (similarities and evaluations above)
✅ Checked embedding dimension (150)
